---

- hosts: localhost
  connection: local
  gather_facts: False
  sudo: True

  tasks:
  - name: launch an instance
    os_server:
      state: present
      auth:
        auth_url: https://keystone.rc.nectar.org.au:5000/v2.0/
        username: j.zhang155@student.unimelb.edu.au
        password: NTJhMDlkZjU1MjYwNDMy
        project_name: CCC2017-Team2
      name: '{{nodename}}'
      image: dcf67de9-edef-45a6-aaf9-de02fcd53208
      key_name: ansible_test
      # region_name: Melbourne
      availability_zone: melbourne-qh2
      timeout: 200
      flavor: '{{flavorid}}'
      security_groups: default,SSH


  - name: create 20g test volume
    os_volume:
      auth:
        auth_url: https://keystone.rc.nectar.org.au:5000/v2.0/
        username: j.zhang155@student.unimelb.edu.au
        password: NTJhMDlkZjU1MjYwNDMy
        # project_name: CCC2017-Team2
        project_id: 561ce2be9d904d998b29d3211f2e623e
      state: present
      availability_zone: melbourne-qh2
      size: 20
      display_name: '{{volumename}}'


  - name: attach volume to host
    os_server_volume:
      auth:
        auth_url: https://keystone.rc.nectar.org.au:5000/v2.0/
        username: j.zhang155@student.unimelb.edu.au
        password: NTJhMDlkZjU1MjYwNDMy
        # project_name: CCC2017-Team2
        project_id: 561ce2be9d904d998b29d3211f2e623e
      state: present
      # cloud: mordred
      server: '{{nodename}}'
      volume: '{{volumename}}'
      device: /dev/vdb