---
- hosts: localhost
  gather_facts: false
  sudo: yes

  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
      state: present
      auth:
        auth_url: https://keystone.rc.nectar.org.au:5000/v2.0/
        username: j.zhang155@student.unimelb.edu.au
        password: NTJhMDlkZjU1MjYwNDMy
        project_name: CCC2017-Team2 
      name: test_VM
      image: dcf67de9-edef-45a6-aaf9-de02fcd53208
      key_name: CCC
      timeout: 200
      flavor: m2.tiny
      # nics:
      #   - net-id: 34605f38-e52a-25d2-b6ec-754a13ffb723
      #   - net-name: another_network
      # meta:
      #   hostname: test1
      #   group: uge_master